# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
randomArr= np.random.randint(1,999,size=(3,3,3))

randomArr

array([[[394, 299, 124],
        [965, 206, 827],
        [841, 125, 106]],

       [[899, 854, 275],
        [335, 312, 959],
        [698, 566, 788]],

       [[445, 252, 501],
        [525, 289, 577],
        [665, 110, 840]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr=np.diag([1,2,3,4], -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
arr1=np.random.random((5,5))
print("Original array is \n",arr1)

from sklearn.preprocessing import normalize

arr2=normalize(arr1)
print("Normalised array is \n",arr2)


Original array is 
 [[0.6250124  0.55422762 0.92844214 0.7524678  0.14300192]
 [0.99361536 0.22482694 0.58985341 0.73710395 0.63054567]
 [0.32005219 0.07362515 0.35958556 0.0411887  0.85095138]
 [0.85465374 0.65955691 0.09665875 0.266994   0.8695175 ]
 [0.04643628 0.44169601 0.44889859 0.98219968 0.32094084]]
Normalised array is 
 [[0.42660519 0.3782907  0.6337126  0.51360047 0.09760664]
 [0.65140672 0.14739484 0.38670343 0.48323977 0.41338097]
 [0.32614768 0.07502736 0.36643397 0.04197315 0.867158  ]
 [0.60400874 0.46612812 0.06831156 0.18869245 0.6145134 ]
 [0.03834593 0.36474158 0.37068929 0.81107607 0.26502496]]


# 5. How to find common values between two arrays?

In [5]:
arr3=np.array([10,20,30,40,60])
print("First array is \n",arr3)

arr4=np.array([20,40,60,80,100])
print("Second  array is \n",arr4)

comarr=np.intersect1d (arr3, arr4)
print("Common elements are ",comarr)


First array is 
 [10 20 30 40 60]
Second  array is 
 [ 20  40  60  80 100]
Common elements are  [20 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)

today     = np.datetime64('today', 'D')
print("Today: ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-10-25
Today:  2020-10-26
Tomorrow:  2020-10-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
randomArr1= np.random.randint(1,10,size=(2,2))
print("First array is\n",randomArr1)

randomArr2= np.random.randint(1,10,size=(2,2))
print("Second array is\n",randomArr2)

if ((randomArr1==randomArr2).all()==True):
    print("Equal ")
else:
    print("Not equal ")

First array is
 [[1 4]
 [9 2]]
Second array is
 [[4 7]
 [9 8]]
Not equal 


# 8.Create random vector of size 10 and replace the maximum value by 0

In [8]:
print("Random vector of size 10:\n")
vect= np.random.randint(1,50, size = 10)
print(vect)

vect[vect.argmax()]=0
print("Vector after replacing the max value to 0 :\n",vect)

Random vector of size 10:

[47 14 42 33 48 38 21 11 47 26]
Vector after replacing the max value to 0 :
 [47 14 42 33  0 38 21 11 47 26]


# 9. How to print all the values of an array?

In [9]:
arr5 = np.arange(51)
np.set_printoptions(threshold=np.inf)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


# 10.Subtract the mean of each row of a matrix

In [10]:
print("Original matrix:\n")
arr6= np.random.randint(1,5,size=(3,4))
print(arr6)

print("\nSubtract the mean of each row of the matrix:\n")
arr7 = arr6-arr6.mean(axis=1, keepdims = True)
print(arr7)


Original matrix:

[[4 1 4 4]
 [1 2 3 1]
 [3 1 4 2]]

Subtract the mean of each row of the matrix:

[[ 0.75 -2.25  0.75  0.75]
 [-0.75  0.25  1.25 -0.75]
 [ 0.5  -1.5   1.5  -0.5 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [11]:
a = np.random.randint(1,8,8)
print("Given vector:", a)

b = np.random.randint(a)
c = []

b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [6 2 3 6 4 1 1 2]
Indexing vector: [0 0 0 0 1 3 3 4]
Result: [7 3 3 7 5 1 1 2]


# 12.How to get the diagonal of a dot product?

In [12]:
x= [[1,2],[3,4]]
y = [[5,6],[7,8]]
z = np.diag(np.dot(x,y))
z

array([19, 50])

# 13.How to find the most frequent value in an array?

In [14]:
arr8= np.random.randint(0, 100, 30)
print("Original array:")
print(arr8)

print("Most frequent value in the above array:")
print(np.bincount(arr8).argmax())


Original array:
[84 65 78  4 50 30 85  4 41 87  5 87 55 82  5 97  9 78 75 24 27 77  0 90
 56 64 69 38 78 79]
Most frequent value in the above array:
78


# 14.How to get the n largest values of an array

In [15]:
x = np.arange(99)
print("Original array:")
print(x)

np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[98]


# 15.How to create a record array from a regular array?

In [16]:
a1=np.array(['Veggie','Tomatoes','Chilli ','Carrot','Lemon'])
a2=np.array(['color','Red','Green','Orange','Yellow'])

result= np.core.records.fromarrays([a1, a2])

print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

('Veggie', 'color')
('Tomatoes', 'Red')
('Chilli ', 'Green')
('Carrot', 'Orange')
('Lemon', 'Yellow')
